### ISSUE TITLE
nuxt 1.0 compatibllity

### ISSUE THREAD

**Issue by husayt** [nuxt/hackernews#10]
Seems this doesn't work with latest Nuxt.
Would be great to update as this is a great demo

**Comment by husayt** [comment]
@pi0 @Atinux just pushed updated version working with latest nuxt and some new features. Works like a charm

**Comment by Atinux** [comment]
Great work @husayt 🙌

**Comment by husayt** [comment]
I forgot to mention, but it is now properly integrated with eslint and prettier. Thanks to that the code has been nicely formatted with vue best practices and passes all eslint checks.
Also added vue server renderer.

Would be great to deploy latest and see its lighthouse mark. This a very powerful showcase for Nuxt and Vue.  We can also use it as example with best practices of nuxt usage.

**Comment by Atinux** [comment]
The app on now.sh has been updated: https://hn.nuxtjs.org :)
