### ISSUE TITLE
Duplicate initial request

### ISSUE THREAD

**Issue by vasisouv** [nuxt/hackernews#114]
When loading the default news initial page the results are server-rendered but the request to fetch the feed is probably performed twice, once on the server and once on the client.

![image](https://user-images.githubusercontent.com/23418601/199685042-6a74d5ac-cc79-4b28-b645-6ded13ca19a3.png)

This is probably due to the usage of `$fetch` without a key.

https://github.com/nuxt/hackernews/blob/b5aadc9b5531be97b77240f1657317ccf0e68b7d/composables/store.ts#L50

Using `$fetch` with some key or the `useFetch` composable would probably solve this.

**Comment by Atinux** [comment]
Actually we leverage `useState` that keep the data from the server to avoid fetching again.

What is weird is that it try to fetch the second page though, any idea @antfu ?

**Comment by vasisouv** [comment]
> Actually we leverage `useState` that keep the data from the server to avoid fetching again.
> 
> What is weird is that it try to fetch the second page though, any idea @antfu ?

Oh nice, that's a good catch, i hadn't notice it was the second page that was being fetched. Maybe it is intended as a prefetching method of the next page.
