### ISSUE TITLE
page error: hn.nuxt.space/item/[id]

### ISSUE THREAD

**Issue by tongweizj** [nuxt/hackernews#132]
HN API had a change that canceled the URL.
https://hacker-news.firebaseio.com/v0/item/35939206.json

So every hn.nuxt.space/item/[id] page, show Page not found.

Please change another key to check wether API back data

**Comment by tongweizj** [comment]
https://hn.nuxt.space/item/35990547

Does it work when you visit this page?
I am the only one that saw the 'Page not found'

**Comment by danielroe** [comment]
no, you are right - I'm getting a 404 too - we can investigate what the issue is

**Comment by tongweizj** [comment]
HN API had changed and did not give  URL data.
https://hacker-news.firebaseio.com/v0/item/35939206.json

**Comment by etherx-dev** [comment]
https://hn.nuxt.space/item/36431004


https://news.ycombinator.com/item?id=36431004 same error

**Comment by danielroe** [comment]
A PR is very welcome 🙏
