### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by SimonSiefke** [nuxt/hackernews#133]
When visiting the demo page at https://hn.nuxt.space, this is all I see:

![emfile](https://github.com/nuxt/hackernews/assets/23744935/1c280238-3584-4815-b3df-6aa17a5d906f)

```
Error: EMFILE: too many open files, open '/var/task/chunks/error-500.mjs'
```

**Comment by antfu** [comment]
It works fine on my side. Maybe a temporary regression on our host service? Do you still see that error now?

**Comment by SimonSiefke** [comment]
It's working fine now:

![nuxt-hacker-news](https://github.com/nuxt/hackernews/assets/23744935/227ec5ea-f7c0-4648-b876-7b5c9d08d3b3)
