### ISSUE TITLE
could not run

### ISSUE THREAD

**Issue by raffacabofrio** [nuxt/hackernews#34]
npm run dev

i got this error:

nuxt dev

sh: nuxt: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nuxt-hn@1.0.0 dev: `nuxt dev`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the nuxt-hn@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2019-08-23T18_33_02_293Z-debug.log

**Comment by phferraz** [comment]
In your project check if your node_modules folder exists, if it does, just delete it. Then run:
>npm install

And try again to run:
>npm run dev
