### ISSUE TITLE
loading is not synced with data

### ISSUE THREAD

**Issue by bluemix** [nuxt/hackernews#6]
Hello, 
I was using (vue-hackernews-2.0)(https://github.com/vuejs/vue-hackernews-2.0) and when I navigate to different pages using _more >_ and _< prev_ , the progress bar is finished correctly when the data fetching is finished.
But here, the loading only keeps synced at the first load, and then always finishes before the data is actually finished fetching.

**Comment by Atinux** [comment]
Should be fixed now!
