### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Wrightlt** [nuxt/hackernews#8]
![b3ac337c-94d8-4c9f-815c-39790f7e23e3](https://user-images.githubusercontent.com/24765382/31328416-a53f9dd4-ac9a-11e7-8b30-f5d37384b700.png)

After the installation can not run, run dev successful but running in the 3000 port has been loading

**Comment by hack2root** [comment]
You doing things wrong, it works out of the box:

DONE  Compiled successfully in 17912ms

 OPEN  http://localhost:3000

  nuxt:render Rendering url / +0ms
  nuxt:render Data fetching /: 2ms +0ms
  nuxt:render Rendering url /top +512ms
  nuxt:render Data fetching /top: 1064ms
