### ISSUE TITLE
Wrong first page

### ISSUE THREAD

**Issue by isagues** [nuxt/hackernews#86]
Hi, is it possible that the New view is fetching a the page number 1 as default instead of page number 0.

I checked the fetch request and is going to `https://hn.nuxtjs.org/api/hn/news?page=1`. When I try that same request but with page=0 y get the top news currently on HN. I couldn't find any other way to view the current top news.

Hope it makes sense

**Comment by antfu** [comment]
This repo is now switched to Nuxt 3 implementation, and I think the issue is no longer relevant. Thanks.
