### ISSUE TITLE
Feeds don't load after deploying SPA

### ISSUE THREAD

**Issue by pjatx** [nuxt/hackernews#90]
For some reason, it appears the feeds aren't loading after deploying to Cloudflare pages in SPA mode. Locally everything works fine. 

I'm able to reproduce if I change lazy -> false here: https://github.com/nuxt/hackernews/blob/8b4413eb4388c3e0ac31cd53aa339084b604a9bd/server/api/hn/index.ts#L20

Anyone know what could be causing this or how to resolve?

**Comment by pjatx** [comment]
Also, appears the SPA demo is also broken in the same way: https://hn-spa.nuxtjs.org/news

**Comment by antfu** [comment]
This repo is now switched to Nuxt 3 implementation, and I think the issue is no longer relevant. Thanks.
